### ISSUE TITLE
nmake command is invalid

### ISSUE THREAD

**Issue by idksomeone0** [jonof/jfbuild#16]
When i do the nmake /f Makefile.msvc command it says nmake isn't a thing, how do i fix this

**Comment by jonof** [comment]
Be sure to pick an appropriate command prompt option in the Start menu.

![startmenu](https://user-images.githubusercontent.com/523647/146283268-01c13456-de7e-4cd9-94e4-66f7df0dbbd7.png)

**Comment by idksomeone0** [comment]
Thanks!

**Comment by idksomeone0** [comment]
I can't find those Command Prompts on the visual studio folder, i can only find one that's just a developer version of command prompt.
