### ISSUE TITLE
Kenbuild music doesn't play on windows

### ISSUE THREAD

**Issue by mankeli** [jonof/jfbuild#24]
Atleast when the game is built with mingw. Can someone confirm if the music works with the msvc build?

**Comment by jonof** [comment]
It works with the MSVC build. You'll notice [in kenbuild/Makefile](https://github.com/jonof/jfbuild/blob/master/kenbuild/Makefile#L90) that on Windows the stub is used.

**Comment by jonof** [comment]
You'd probably be better off spending the time trying to get the XAudio2 kdmsound file compiling and linking with MinGW32, since that's what the MSVC variant uses. SDL2 audio should already work on Windows if you select that RENDERTYPE instead of the normal WIN one.
