### ISSUE TITLE
Missing `tables.dat`

### ISSUE THREAD

**Issue by computermouth** [jonof/jfbuild#7]
Freshly compiled, Debian 8:

```
  - 320x200 24-bit windowed
There was a problem initialising the Build engine: Failed to load TABLES.DAT!
   (press Return or Enter to continue)
```

No copy of `TABLES.DAT` or `tables.dat` is in the source.

**Comment by computermouth** [comment]
My bad! Looks like I just need to RTFM. Thanks

**Comment by jonof** [comment]
I should probably make it clearer, and I suppose there's an argument for embedding the two tables into the executable for a clean-sheet project to start with. Someone would simply need to provide a palette and create empty .art files and they'd be on their way.

**Comment by computermouth** [comment]
Personally, I'd been watching a bunch of videos about old engines, and had wanted to try it out. I was coming into it cold without having even played the games that were published with the engine.

It looks like you've done great work to modernize the code itself, but it'd be lovely to also have a modernized documentation, like a HOWTO or a HELLO_KENBUILD example.
