### ISSUE TITLE
Unable to build this on macOS

### ISSUE THREAD

**Issue by hogsy** [jonof/jfbuild#8]
Getting the following for everything when typing in 'make'.

```
error: No signing certificate "Mac Development" found: No "Mac Development" signing certificate matching team ID "S7U4E54CHC" with a private key was found.
```

**Comment by jonof** [comment]
You will need to open the Xcode game (and/or engine) project and update the code signing settings to use your developer identity. I haven't figured out how to keep that information separate from the project yet.

**Comment by hogsy** [comment]
That did the trick, thanks!
